language: node_js
node_js:
  - "7"

sudo: required
dist: trusty
before_install:
  # https://launchpad.net/~thomas-schiex/+archive/ubuntu/blender
  - sudo add-apt-repository ppa:thomas-schiex/blender -y
  - sudo apt-get update
  - sudo apt-get install blender -y
before_script:
  - node_modules/.bin/node-babylonjs-blender-install
after_success:
  - curl -sL https://raw.githubusercontent.com/travis-ci/artifacts/master/install | bash
  - export ARTIFACTS_PATHS=$(find build -type f -printf ':%h/%f' | tail -c +2)
  - export ARTIFACTS_TARGET_PATHS=${TRAVIS_REPO_SLUG}/${TRAVIS_BUILD_NUMBER}/${TRAVIS_JOB_NUMBER}
  - DO_DEPLOY=$([ "${TRAVIS_PULL_REQUEST}" == false ] && [ "${TRAVIS_BRANCH}" == master ] && echo true || echo false)
  - echo DO_DEPLOY="${DO_DEPLOY}"
  - [ "${DO_DEPLOY}" == true ] && artifacts -D upload
  - curl https://sam.ohnopub.net/~faito/webhook-pull/index.cgi/simple/faito/"${WEBHOOK_PULL_KEY}"/
