language: node_js
node_js:
  - "7"

sudo: required
dist: trusty
before_install:
  # https://launchpad.net/~thomas-schiex/+archive/ubuntu/blender
  - sudo add-apt-repository ppa:thomas-schiex/blender -y
  - sudo apt-get update
  - sudo apt-get install blender -y
before_script:
  - node_modules/.bin/node-babylonjs-blender-install
addons:
  artifacts:
    paths:
      - $(find build -type f -printf ':%h/%f' | tail -c +2)
# Use deploy because it runs after the artifacts are uploaded.
deploy:
  provider: script
  script: curl https://sam.ohnopub.net/~faito/webhook-pull/index.cgi/simple/faito/"${WEBHOOK_PULL_KEY}"/
